version: '3'

services:
  # MySQL
  db:
    image: mysql:5.7
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: uzomuzo
      MYSQL_PASSWORD: uzomuzo
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  web:
    image: openjdk11
    environment:
      MYSQL_URL: jdbc:mysql://mysql_host:3306/tsk2?useSSL=false
    container_name: tsk2web
    build: ../server/
#    volumes:
#      - ./docker/web/data:/tmp
    ports:
      - 80:8080
