spring:
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://mysql_host:3306/tsk2?useSSL=false
    url: ${MYSQL_URL:jdbc:mysql://mysql_host:3306/tsk2?useSSL=false}
    username: ${MYSQL_USER_NAME:root}
    password: ${MYSQL_PASSWORD:root}
    validationQuery: SELECT 1
    testOnBorrow: true
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: ConnectionPool
      leakDetectionThreshold: 5000
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: false
  jooq:
    sql-dialect: mysql
  liquibase:
    enabled: false