openapi: "3.0.0"
info:
  version: 1.0.0
  title: tsk2 todo
  license:
    name: MIT
servers:
  - url: http://{environment}:{port}/
    variables:
      environment:
        default: localhost    # Development server
        enum:
          - api.tsk2.me # Production server
          - localhost   # Development server
      port:
        default: 8080    # Development server
        enum:
          - 80     # Production server
          - 8080   # Development server
paths:
  /health:
    get:
      summary: health check
      operationId: healthCheck
      tags:
        - health
      responses:
        '200':
          description: OK
  /tasks:
    options:
      tags:
        - tasks
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
    get:
      summary: List all tasks
      operationId: tasksGet
      tags:
        - tasks
      responses:
        '200':
          description: A paged array of tasks
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TasksDTO"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      tags:
        - tasks
      description: やることの登録
      operationId: taskPost
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreateDTO'
      responses:
        '201':
          description: やることの作成成功
          content:
            application/json:
              schema:
                type: integer
                format: int64
  /tasks/{id}:
    delete:
      tags:
        - tasks
      description: やることの削除
      operationId: taskDelete
      parameters:
        - name: id
          in: path
          required: true
          description: tasks id
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: delete success

components:
  schemas:
    TaskDTO:
      required:
        - id
        - title
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
    TasksDTO:
      type: array
      items:
        $ref: "#/components/schemas/TaskDTO"
    TaskCreateDTO:
      required:
        - title
      properties:
        title:
          type: string
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string